// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import '../backend/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXC4E0_9QAS6WgaLfKrWonexeS46gqHto',
    appId: '1:659375422936:web:f8df72dbebfc87f87a86ad',
    messagingSenderId: '659375422936',
    projectId: 'mindora-7d752',
    authDomain: 'mindora-7d752.firebaseapp.com',
    storageBucket: 'mindora-7d752.firebasestorage.app',
    measurementId: 'G-20RVVLMFNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAh8AIlXxROVaD0MCuY9QCPgV37R-Y8b6o',
    appId: '1:659375422936:android:05dd09e88c9d05e07a86ad',
    messagingSenderId: '659375422936',
    projectId: 'mindora-7d752',
    storageBucket: 'mindora-7d752.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARVcivVi4vRhhJInnpmjV8va-HXHp-FWg',
    appId: '1:659375422936:ios:7dd4ad631c96d9c77a86ad',
    messagingSenderId: '659375422936',
    projectId: 'mindora-7d752',
    storageBucket: 'mindora-7d752.firebasestorage.app',
    iosBundleId: 'com.example.mindoraTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARVcivVi4vRhhJInnpmjV8va-HXHp-FWg',
    appId: '1:659375422936:ios:7dd4ad631c96d9c77a86ad',
    messagingSenderId: '659375422936',
    projectId: 'mindora-7d752',
    storageBucket: 'mindora-7d752.firebasestorage.app',
    iosBundleId: 'com.example.mindoraTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXC4E0_9QAS6WgaLfKrWonexeS46gqHto',
    appId: '1:659375422936:web:c1f1d3269c799ee87a86ad',
    messagingSenderId: '659375422936',
    projectId: 'mindora-7d752',
    authDomain: 'mindora-7d752.firebaseapp.com',
    storageBucket: 'mindora-7d752.firebasestorage.app',
    measurementId: 'G-2R03YWVR93',
  );
}

